services:
  app:
    build: .
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
    ports:
      - "80:3000"
      - "443:3000"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./sockio/:/app/sockio/
      - ./.env:/app/.env
    networks:
      - sockio_network
    command: [ "uv", "run", "watchfiles","sockio.main.main" ]

  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=sockio_db
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - sockio_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  sockio_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local