services:
  app:
    build: .
    container_name: sockio_app
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
    ports:
      - "80:3000"
      - "443:3000"
    volumes:
      - ./sockio/:/app/sockio/
    command: [ "uv", "run", "watchfiles","sockio.main.main" ]
