services:
  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    networks:
      - sockio_network
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  sockio_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
