services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sockio_network
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sockio
      - POSTGRES_USER=sockuser
      - POSTGRES_PASSWORD=sockpass
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "sockuser" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  sockio_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
