[project]
name = "sockio"
version = "0.1.0"
description = "Fast messanger"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "socketify>=0.0.31",
    "watchfiles>=1.1.0",
]


[tool.uv]
dev-dependencies = [
    "websockets>=15.0.1"
]