name: Deployment
on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy files to VPS
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@${{ secrets.VPS_HOST }}:/opt/sockio/

      - name: Run docker compose on VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} \
          "cd /opt/sockio && docker compose up -d --build"
